### ISSUE TITLE
[BUG] demo tests contain deprecated functions

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cuspatial#312]
The demo tests contain functions that have been deprecated from cuspatial. Therefore, the tests do not run

**Comment by harrism** [comment]
What are the "demo tests"? Can you provide a link?

**Comment by zhangjianting** [comment]
Python demo code is under python/cuspatial/demos. They were mostly developed last summer and are outdated. Some of these demos can not run out-of-box anyway as they rely on external data. I would suggest remove these demo code as they are not essential to cuspatial as a library.   

Alternatively, I am thinking the suitability of creating a new repo outside of cuspatial to host demo codes for apps using both public or private data for performance test. In this way, demo/app code (using C++/Python/Java APIs) does not need to go through code review process by cuspatial team. This may attract more contributors  who are more users (including some researchers) rather than developers, or those who do not have sufficient knowledge of cuda/cudf to develop production level code and make direct contributions to cuspatial.  As a first step, when I get a chance, I will refactorize some of these outdated demo code and put them on my personal github repo as a new project.

**Comment by harrism** [comment]
I recommend just putting such notebooks in https://github.com/rapidsai-community/notebooks-contrib

**Comment by thomcom** [comment]
@Salonijain27 are you referring to the code snippets in `python/cuspatial/demos`? If so, I agree with Jianting that we should remove them.

**Comment by thomcom** [comment]
@taureandyernv is talking about creating notebooks from these. Lets delete them and move on with the notebooks work.
