### ISSUE TITLE
API to extract a subset of polygons from existing set

### ISSUE THREAD

**Issue by harrism** [rapidsai/cuspatial#507]
It would be great if we can have a Python API like `subset_polygon_geodataframe(geo_df,subset_ids or subset_range)` to return the same four arrays like `read_polygon_shapefile(shp_file)`. This will leave the C++ API untouched and could be more efficient than saving subset of polygons to shapefile and then read the saved shapefile back (round-trip to disk), especially for large polygon datasets.

_Originally posted by @zhangjianting in https://github.com/rapidsai/cuspatial/issues/492#issuecomment-1082543191_

**Comment by thomcom** [comment]
Hi Mark! I never saw this issue until the `inactive-90d` flag.

You can do this now:

`geo_series._column.polygons._column.base_children[0]` returns `read_polygon_shapefile(...)[0]`
`geo_series._column.polygons._column.base_children[1].base_children[0]` returns `read_polygon_shapefile(...)[1]`
`geo_series._column.polygons.x` returns `read_polygons_shapefile(...)[2].x`
`geo_series._column.polygons.y` returns `read_polygons_shapefile(...)[2].x`

While these conversions are somewhat cumbersome, this is because it would be better to refactor `point_in_polygon` in python, for example, to be `points_series.sjoin(polygons_series)` than to make the underlying GeoArrow buffers more accessible but keep the API surface what it is. Don't you agree?

**Comment by thomcom** [comment]
This was closed in https://github.com/rapidsai/cuspatial/pull/660.

Mark, you can access the underlying offset members of polygons with:

```
geoseries.polygons.geometry_offset # for the multipolygons offsets
geoseries.polygons.part_offset # for the polygon offsets
geoseries.polygons.ring_offset # for the rings offsets
```
