### ISSUE TITLE
[DOC] Point-in-polygon documentation doesn't specify the need to repeat polygon start coord as end coord

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cuspatial#51]
**Describe the bug**
A close enough review of the point-in-polygon example code could reveal this, but it is not at all obvious. Polygons specified as input to this function need to be closed - their starting vertex must be the same as the ending vertex.

Clarify this in the docs.

**Comment by MurrayData** [comment]
Some GIS libraries allow "autoclose" as an option for unclosed rings, but generally standards dictate the ring should be closed and clockwise if exterior ring and counter-clockwise if interior ring. In latter case test needs to be negated, i.e. if the point is in the ring (i.e. a hole), then the point is outside.

e.g. this is the polygon of my local hospital main building.

![image](https://user-images.githubusercontent.com/8914493/64857456-7d3ba500-d61c-11e9-8a14-5347af230421.png)

The file below contains this polygon, in ESRI WKT (Well Known Text) format with coordinates in WGS84 for testing.

[coch_polygon_wkt.txt](https://github.com/rapidsai/cuspatial/files/3609684/coch_polygon_wkt.txt)

Another example is this example of a UK Parliamentary Constituency which has multiple exterior rings as it represents a group of islands.

![orkney_islands](https://user-images.githubusercontent.com/8914493/64857923-d3f5ae80-d61d-11e9-8202-e0db92a91c36.png)

I can provide plenty of test data if you require it.

**Comment by zhangjianting** [comment]
cuSpatial polygon representation follows OGC standard. For real world data, they are likely to be automatically derived from some well-known formats (e..g, ESRI shapefiles and WKT) as opposed to manually hard-coding (no one would want to do that). As such, the conventions, including enclosing rings with first and last vertices have the same coordinates are naturally satisfied. 
Johh: the implemented algorithm should work for multi-polygons and/or polygon with holes (due to Prof. Franklin at RPI), but I have not had the chance to test polygons with holes inside holes. Do you have such a test case? If cuSpatial does not support these special cases, it should be documented.

**Comment by zhangjianting** [comment]
@MurrayData where did you get the WKT data? I am looking for polygons with holes and the data seems meet my criteria. The problem is that, although the WKT is valid for shapely and I was able to convert it into a shapefile using Fiona, the shapefile behaves strangely in ArcGIS (ArcMap Desktop). I was told that the polygon (feature) has invalid geometry and many queries in ArcGIS have incorrect results. It seems that the WKT does not follow OGC standard and has orientation/enclosing issues (https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry). Do you have additional real world polygons with holes? I searched quite a few NYC zonal datasets and could not find any.
