### ISSUE TITLE
[QST]Do all coordinates for points/polygons/lines need to be in WGS84 lat/lon prior to being used by cuSpatial?

### ISSUE THREAD

**Issue by yidong72** [rapidsai/cuspatial#78]
•	Is there any requirement for “OGC validity” of polygons?  Issues such as self-intersections, “back tracking”, repeating points, etc. can be problematic at times.  https://www.opengeospatial.org/standards/sfa 
•	Are there any min/max latitude ranges?  Sometimes things go bad if approaching either north or south pole.
•	Are there any special considerations for polygons or lines that cross the +/- 180 degree longitude line?  For example, hurricane tracks/windfields near Fiji and New Zealand or the Aleutian Islands of Alaska (Attu), or the coastline of Russia.
•	Winding order of exterior/interior rings?
Thanks

**Comment by zhangjianting** [comment]
Currently cuSpatial is designed as a set of APIs to speed up certain geospatial operations instead of a complete framework/platform to replace existing ones. As such, cuSpatial assumes the inputs are valid which can be checked by existing third-party packages. With more resources available and more community contributions, it is possible to add new modules/features for robustness. 
for the last question, cuSpatial follows ESRI shapefile standard on vertex orientation and supports multi-polygons and/or polygons with multiple rings. For polygons with multiple rings, the first ring is the exterior ring and the others are interior rings. Please also see discussions at https://github.com/rapidsai/cuspatial/issues/51

**Comment by harrism** [comment]
> Do all coordinates for points/polygons/lines need to be in WGS84 lat/lon prior to being used by cuSpatial?

No. Generally the APIs apply to Cartesian coordinates, except `lonlat_to_cartesian`. If the documentation for a specific function is not clear on this, please open a doc issue.

cuSpatial doesn't currently support coordinate reference systems and does not currently provide projection between coordinate systems, but this is something we are starting to explore.

Closing this now as answered.
